name: "Deploy to GKE"

on:
  push:
    branches:
      - main  # Triggers the robot only when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # These permissions are required for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # 1. Authenticate with Google Cloud using WIF
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/638568717503/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'my-service-account@devops-mastery-2026.iam.gserviceaccount.com'

    # 2. Get GKE Credentials
    - name: 'Set up GKE Credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'ops-mastery-cluster'
        location: 'us-central1'

    # 3. Deploy to Kubernetes
    - name: 'Deploy Microservices'
      run: |
        kubectl apply -f ./release/kubernetes-manifests.yaml
