name: "Deploy to GKE"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/638568717503/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        # FIXED: Using the actual service account name
        service_account: 'github-robot@devops-mastery-2026.iam.gserviceaccount.com'

    - name: 'Set up GKE Credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'ops-mastery-cluster'
        location: 'us-central1'

    - name: 'Deploy Microservices'
      run: |
        kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/release/kubernetes-manifests.yaml
